name: My Workflow
on: [push]
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello, world!"

    - name: List current gilder
      run: ls -la
